name: Java CI with Maven

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set env
        run: echo "RELEASE_VERSION=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
      - name: Build with Maven
        env:
          DOCKER_REGISTRY_URL: docker.io
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: mvn compile jib:build -Djib.to.auth.username=projecteka -Djib.to.auth.password=${DOCKER_PASSWORD} -Dimage=projecteka/monitor-db-initializer:${RELEASE_VERSION}
